spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ums
    username: sa
    password:
myapp:
  mail:
    host: test123456@test.com
    port: 22222
    username: bkkim123456
    password: bkkim123456