spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    bootstrap-servers: kafka:${KAFKA_PORT:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      group-id: test-group
      key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  data:
    redis:
      host: redis
      port: 6379
myapp:
  mail:
    host: test123456@test.com
    port: 22222
    username: jang3142
    password: jang3142

email:
  security:
    owner-password: test

template:
  upload:
    bucket: ums-proj-bucket-01
    prefix-key: /template
  email:
    template-key-prefix: /template
    image-key-suffix: images
    attachment-key-suffix: attachment



target:
  upload:
    bucket: ums-proj-bucket-01
    prfix-key: /target/upload
    download-key:
    upload-max-size:


