spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ums
    username: sa
    password:
myapp:
  mail:
    host: test123@test.com
    port: 22222
    username: jang3142
    password: jang3142