spring:
  config:
    import:
      - configserver:kafka.yml
      - configserver:redis.yml
      - configserver:datasource.yml
myapp:
  mail:
    host: test@test.com
    port: 2222
    username: jang314
    password: jang314