spring:
  config:
    import:
      - optional:https://ums-config-file-bucket.s3.ap-northeast-2.amazonaws.com/ums-config-file/kafka.yml
      - optional:https://ums-config-file-bucket.s3.ap-northeast-2.amazonaws.com/ums-config-file/redis.yml
      - optional:https://ums-config-file-bucket.s3.ap-northeast-2.amazonaws.com/ums-config-file/datasource.yml
myapp:
  mail:
    host: test@test.com
    port: 2222
    username: jang314
    password: jang314