spring:
  config:
    import:
      - optional:file:./kafka.yml
      - optional:file:./redis.yml
      - optional:file:./datasource.yml
myapp:
  mail:
    host: test@test.com
    port: 2222
    username: jang314
    password: jang314