spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ums
    username: sa
    password:
myapp:
  mail:
    host: test@test.com
    port: 2222
    username: jang314
    password: jang314