spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/app/db/schedule;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
myapp:
  mail:
    host: test1@test.com
    port: 2222
    username: jang316
    password: jang316