spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ums
    username: sa
    password:
myapp:
  mail:
    host: happyman@test.com
    port: 22222
    username: happyman
    password: happyman
